Implement simple InfluxDB client
TulipaEnergy/TulipaIO.jl pull request #19
Opened 2024-03-06 09:30 UTC by wcoenraads

Adds a simple InfluxDB client as described in #6. It's important to note that the current implementation does not escape the parameters to the query, so it should not be used with untrusted input.

2024-03-15 21:43 UTC, suvayu requested changes
A few comments:
- Could you wrap the client in a module so that everything InfluxDB is in its own namespace?
  ```julia
  module Influx
  # contents of influx.jl
  end # module InfluxDB
  ```
- With the above change, maybe it is best to rename `InfluxClient` to just `Client`
- Do you have any idea how to write tests for this module?

2024-03-15 21:43 UTC, suvayu commented on src/influx.jl
> +end
I don't think this kind of convenience constructors should be inner.  You should move this to outer, then you cannot use `new`.  So, probably this:

```suggestion
end

InfluxClient(
    host::String,
    database::String,
) = InfluxClient(host, database, 8086, "query", "", "")
```

2024-04-03 13:22 UTC, clizbe commented
@wcoenraads Is this waiting on Suvayu's return?

2024-04-08 09:31 UTC, wcoenraads commented
These comments/notifications completely passed me by - apologies! I'll address your comments and update the PR this afternoon.

As for testing, I'm also unsure. Downstream tests relying on these APIs could use mock data, but the influx client should really be tested against the InfluxDB API as that's the thing it interacts with. We could create a setup with a development DB to test against, but that feels like a lot of effort for little gain at the moment.

2024-04-08 12:02 UTC, wcoenraads commented
>     * Could you wrap the client in a module so that everything InfluxDB is in its own namespace?
>       ```julia
>       module InfluxDB
>       # current contents of influx.jl
>       end # module InfluxDB
>       ```
> 
>     * With the above change, maybe it is best to rename `InfluxClient` to just `Client`

Good point on the module! 

I've renamed `InfluxClient` to `InfluxDBClient` to stay consistent with the [official API](https://influxdb-client.readthedocs.io/en/stable/api.html#influxdbclient). I'm also not super familiar with the conventional way to do imports in Julia, but I assume using `InfluxDBClient` instead of just `Client` should also help prevent conflicts when importing it.

2024-04-08 12:38 UTC, suvayu commented
**PS:** I think the nightly test failure is due to an upstream packaging issue, ignore for now.

2024-04-08 12:50 UTC, wcoenraads commented
> I think it would be more consistent if the file was called `influxdb.jl`.

Yep, good point - changed!

>  I can think of two approaches:
> [....]

The first approach could work, but seems limited and fragile: tests that can't be run in CI are much less likely to be adhered to, and they would depend on the specifics of an internal DB we only have limited control over.

The second approach is solid, but indeed more work. It might also be beneficial in tests for later components, where we can do end-to-end tests without mocks in between. But that's a concern for later.

2024-04-08 13:06 UTC, merged

2024-04-08 13:08 UTC, suvayu commented
Thanks! I merged this, we can workout the tests in a separate PR.

2024-04-08 15:33 UTC, clizbe commented
Closes #6